# Generated by Django 4.0.3 on 2024-08-08 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_href', models.URLField(unique=True)),
                ('closet_name', models.CharField(max_length=200)),
                ('section_number', models.PositiveIntegerField()),
                ('shelf_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=200)),
                ('fabric', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=50)),
                ('picture_url', models.URLField()),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hats', to='hats_rest.locationvo')),
            ],
        ),
    ]
