# Generated by Django 4.0.3 on 2024-08-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_alter_binvo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binvo',
            options={},
        ),
    ]
